"""One-shot script to enrich define() in all components/*/working.py files.
Run from the project root.
"""
from __future__ import annotations
import re
from pathlib import Path

# ── helpers ──────────────────────────────────────────────────────────────────

def _v(*args):
    """Build a variable dict."""
    name, description, typ, default = args
    return {"name": name, "description": description, "type": typ, "default": default}

ROT_VARS = [
    _v("rot",   "Rotation [rx,ry,rz] in degrees.",           "list",   "[0,0,0]"),
    _v("rot_x", "X rotation in degrees.",                     "number", 0),
    _v("rot_y", "Y rotation in degrees.",                     "number", 0),
    _v("rot_z", "Z rotation in degrees.",                     "number", 0),
]

POS_VAR   = _v("pos", "3-element [x,y,z] position.",         "list",   "[0,0,0]")
TYPE_VAR  = _v("type","Geometry type: p/positive or n/negative.", "string", "p")
MODE_VAR  = _v("mode","Render modes: laser, 3dpr, true.",     "list",   '["laser","3dpr","true"]')
PART_VAR  = _v("part","Part selector (all, only_holes, shaft, ...).", "string", "all")
EXTRA_VAR = _v("extra","Extra variant/modifier string.",      "string", '""')
CLEARANCE_VAR = _v("clearance","Clearance extension sides: top, bottom.", "list", '["top","bottom"]')

# ── define data ───────────────────────────────────────────────────────────────

DEFINES = {
    # ── oobb geometry primitives ────────────────────────────────────────────
    "oobb_circle": dict(
        name_long="OOBB Geometry Primitives: Circle",
        description="Renders a cylinder (solid or cutout) sized to an OOBB grid position.",
        category="OOBB Geometry Primitives",
        shape_aliases=["circle"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR,
            _v("width",    "Width in OOBB grid units.",           "number", 1),
            _v("height",   "Height in OOBB grid units.",          "number", 1),
            _v("depth",    "Z depth (height) of the cylinder in mm.", "number", 3),
            _v("extra_mm", "Adds 1/15 to width/height for clearance fit.", "bool", False),
            _v("zz",       "Z anchor point: bottom, top, middle.", "string", '"bottom"'),
        ],
    ),
    "oobb_coupler_flanged": dict(
        name_long="OOBB Mechanical: Flanged Coupler",
        description="Flanged coupler with shaft holes and flange M3/M8 cutouts, wrapped in a rotation object.",
        category="OOBB Mechanical",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("part", "Which part to generate: all, only_holes, shaft.", "string", '"all"'),
            *ROT_VARS,
        ],
    ),
    "oobb_cube": dict(
        name_long="OOBB Geometry Primitives: Cube",
        description="Cube geometry primitive; delegates to oobb_cube_center.",
        category="OOBB Geometry Primitives",
        shape_aliases=["cube"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR,
            _v("size", "[x,y,z] dimensions in mm.", "list", "(required)"),
            _v("zz",   "Z anchor point: bottom, top, center/middle.", "string", '"bottom"'),
        ],
    ),
    "oobb_cube_center": dict(
        name_long="OOBB Geometry Primitives: Cube Center",
        description="Center-aligned cube that shifts pos by -size/2 on x/y before passing to OpenSCAD.",
        category="OOBB Geometry Primitives",
        shape_aliases=["cube_center"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR,
            _v("size", "[x,y,z] dimensions in mm.", "list", "(required)"),
            _v("zz",   "Z anchor point: bottom, top, center/middle.", "string", '"bottom"'),
        ],
    ),
    "oobb_cube_new": dict(
        name_long="OOBB Geometry Primitives: Cube New",
        description="Cube with full rotation-object support and mode filtering.",
        category="OOBB Geometry Primitives",
        shape_aliases=["cube_new"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("size", "[x,y,z] dimensions in mm.", "list", "(required)"),
            _v("zz",   "Z anchor point: bottom, top, center/middle.", "string", '"bottom"'),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_cylinder": dict(
        name_long="OOBB Geometry Primitives: Cylinder",
        description="Cylinder geometry across all render modes, supporting named or explicit radius and z-centering.",
        category="OOBB Geometry Primitives",
        shape_aliases=["cylinder"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR,
            _v("depth",       "Cylinder height in mm.",                  "number", 250),
            _v("radius_name", "Named radius for mode-aware lookup.",      "string", '""'),
            _v("radius",      "Explicit radius in mm.",                   "number", 0),
            _v("zz",          "Z anchor point: center, bottom, top.",     "string", '"center"'),
        ],
    ),
    "oobb_cylinder_hollow": dict(
        name_long="OOBB Geometry Primitives: Hollow Cylinder",
        description="Hollow cylinder (positive outer minus negative inner) wrapped in a rotation object.",
        category="OOBB Geometry Primitives",
        shape_aliases=["cylinder_hollow"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("r",              "Outer radius in mm.",                    "number", "(required)"),
            _v("wall_thickness", "Wall thickness for inner cylinder.",     "number", 2),
            _v("depth",          "Cylinder height in mm.",                 "number", "(required)"),
            *ROT_VARS,
        ],
    ),
    "oobb_electronic_battery_box_aa_battery_4_cell": dict(
        name_long="OOBB Electronics: 4×AA Battery Box",
        description="4×AA battery box cutout set with body, countersunk screws, and wire-clearance cubes.",
        category="OOBB Electronics",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR, PART_VAR,
            _v("depth_screw", "Depth of countersunk screw cutouts.", "number", 6),
            EXTRA_VAR, *ROT_VARS,
        ],
    ),
    "oobb_electronic_button_11_mm_panel_mount": dict(
        name_long="OOBB Electronics: 11mm Panel Mount Button",
        description="11 mm panel-mount push-button cutout with optional clearance extension.",
        category="OOBB Electronics",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR, PART_VAR, CLEARANCE_VAR, EXTRA_VAR, *ROT_VARS,
        ],
    ),
    "oobb_electronic_potentiometer_17_mm": dict(
        name_long="OOBB Electronics: 17mm Potentiometer",
        description="17 mm potentiometer cutout with shaft cylinders, keying cube, and wire-clearance cubes.",
        category="OOBB Electronics",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR, PART_VAR, CLEARANCE_VAR, EXTRA_VAR, *ROT_VARS,
        ],
    ),
    "oobb_electronic_potentiometer_stick_single_axis_16_mm": dict(
        name_long="OOBB Electronics: 16mm Single-Axis Joystick",
        description="16 mm single-axis joystick/potentiometer cutout with body, foot cubes, and stick hole.",
        category="OOBB Electronics",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR, PART_VAR, CLEARANCE_VAR, EXTRA_VAR,
            _v("width_stick", "Radius of the stick shaft hole.", "number", 2),
            *ROT_VARS,
        ],
    ),
    "oobb_hole_new": dict(
        name_long="OOBB Geometry Primitives: Hole",
        description="Cylindrical hole with rotation-object support, mode filtering, and named/explicit radius.",
        category="OOBB Geometry Primitives",
        shape_aliases=["hole_new"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("depth",       "Hole depth in mm.",                      "number", 100),
            _v("radius_name", "Named radius for mode-aware lookup.",     "string", '""'),
            _v("radius",      "Explicit radius in mm.",                  "number", 0),
            _v("zz",          "Z anchor: bottom, top, middle.",          "string", '"middle"'),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_mechanical_motor_with_encoder_30_mm_diameter_cricut_maker_compatible": dict(
        name_long="OOBB Mechanical: 30mm Motor with Encoder (Cricut Compatible)",
        description="30 mm diameter Cricut-compatible motor-with-encoder cutout set (shaft hole + M2.5 mounting holes).",
        category="OOBB Mechanical",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR, PART_VAR, *ROT_VARS,
        ],
    ),
    "oobb_motor_servo_standard_01": dict(
        name_long="OOBB Mechanical: Standard Servo Motor",
        description="Standard servo motor cutout with shaft hole, M3 mounting holes, optional screws, body cube, and overhang support.",
        category="OOBB Mechanical",
        shape_aliases=["motor_servo_standard_01"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("part",             "Part selector: all, only_holes.",     "string", '"all"'),
            _v("include_screws",   "Include socket-cap screw cutouts.",   "bool",   True),
            _v("overhang",         "Add overhang support geometry.",      "bool",   True),
            CLEARANCE_VAR,
            _v("screw_rot_y",      "Rotate screw head 180° on Y.",        "bool",   False),
            _v("screw_depth",      "Depth of mounting screw holes.",      "number", 8),
            _v("screw_depth_shaft","Depth of shaft screw hole.",          "number", 6),
            EXTRA_VAR, *ROT_VARS,
        ],
    ),
    "oobb_motor_stepper_nema_17": dict(
        name_long="OOBB Mechanical: NEMA-17 Stepper Motor",
        description="NEMA-17 stepper motor cutout with shaft hole, four M3 mounting holes, optional screws/spacers, and clearance cubes.",
        category="OOBB Mechanical",
        shape_aliases=["motor_stepper_nema_17"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("part",             "Part selector: all, only_holes, spacer, shaft.", "string", '"all"'),
            _v("include_screws",   "Include screw cutouts.",              "bool",   True),
            _v("overhang",         "Add overhang support geometry.",      "bool",   True),
            CLEARANCE_VAR,
            _v("thickness",        "Plate thickness for screw positioning.", "number", 0),
            _v("spacer_depth",     "Depth of spacer cylinders.",          "number", 0),
            _v("screw_rot_y",      "Rotate screw head 180° on Y.",        "bool",   False),
            _v("screw_depth",      "Depth of mounting screw holes.",      "number", 8),
            EXTRA_VAR, *ROT_VARS,
        ],
    ),
    "oobb_motor_tt_01": dict(
        name_long="OOBB Mechanical: TT Motor",
        description="TT-motor cutout with 26 mm shaft hole, M6 clearance hole, and countersunk mounting screws.",
        category="OOBB Mechanical",
        shape_aliases=["motor_tt_01"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR, PART_VAR,
            _v("screw_lift",    "Z lift applied to mounting screw positions.", "number", 3),
            _v("radius_extra",  "Extra radius added to shaft hole.",           "number", 0.4),
            _v("thickness",     "Plate thickness used in screw positioning.",  "number", 3),
            CLEARANCE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_nut": dict(
        name_long="OOBB Geometry Primitives: Nut",
        description="Hexagonal nut pocket with optional through-hole, overhang, and clearance, across all render modes.",
        category="OOBB Geometry Primitives",
        shape_aliases=["nut"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("radius_name",      "Named radius key, e.g. m3, m6.",          "string", '"m3"'),
            _v("zz",               "Z anchor: bottom, top, middle.",           "string", '"bottom"'),
            _v("depth",            "Nut pocket depth in mm.",                  "number", '""'),
            _v("overhang",         "Add overhang support geometry.",           "bool",   False),
            _v("clearance",        "Clearance extension sides.",               "string", '""'),
            _v("hole",             "Include a through-hole below the nut.",    "bool",   False),
            _v("extra_clearance",  "Extra mm added to side clearance height.", "number", 0),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_overhang": dict(
        name_long="OOBB Geometry Primitives: Overhang Bridge",
        description="Two-layer 3D-print overhang bridge geometry sized to a named radius footprint.",
        category="OOBB Geometry Primitives",
        shape_aliases=["overhang"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR,
            _v("radius_name", "Named radius key: m3, m3_nut, m2, m6.", "string", '"m3"'),
            _v("zz",          "Z anchor: bottom, other.",               "string", '"bottom"'),
        ],
    ),
    "oobb_plate": dict(
        name_long="OOBB Geometry Primitives: Plate",
        description="OOBB grid-sized plate (cylinder for 1×1, rounded rectangle otherwise) with optional hole pattern.",
        category="OOBB Geometry Primitives",
        shape_aliases=["plate"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR,
            _v("width",    "Width in OOBB grid units.",            "number", 1),
            _v("height",   "Height in OOBB grid units.",           "number", 1),
            _v("depth",    "Plate thickness in mm.",               "number", 3),
            _v("zz",       "Z anchor: bottom, top, middle.",       "string", '"bottom"'),
            _v("extra_mm", "Adds 1/15 to size for clearance fit.", "bool",   False),
            _v("holes",    "Include OOBB hole pattern.",           "bool",   False),
        ],
    ),
    "oobb_rot": dict(
        name_long="OOBB Geometry Helpers: Rotation Helper",
        description="Helper that extracts and returns a [rx,ry,rz] rotation list from kwargs.",
        category="OOBB Geometry Helpers",
        shape_aliases=[],
        returns="List [rx, ry, rz].",
        variables=[
            _v("rot",   "Explicit [rx,ry,rz] rotation list; returned directly if present.", "list",   '""'),
            _v("rot_x", "X rotation in degrees.", "number", 0),
            _v("rot_y", "Y rotation in degrees.", "number", 0),
            _v("rot_z", "Z rotation in degrees.", "number", 0),
        ],
    ),
    "oobb_rounded_rectangle_hollow": dict(
        name_long="OOBB Geometry Primitives: Hollow Rounded Rectangle",
        description="Hollow rounded rectangle (positive outer minus negative inner wall) wrapped in a rotation object.",
        category="OOBB Geometry Primitives",
        shape_aliases=["rounded_rectangle_hollow"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("size",           "Outer [x,y,z] dimensions in mm.",      "list",   "(required)"),
            _v("radius",         "Corner radius of outer shape.",         "number", "(required)"),
            _v("wall_thickness", "Wall thickness from outer to inner.",   "number", 2),
            EXTRA_VAR, *ROT_VARS,
        ],
    ),
    "oobb_rounded_rectangle_rounded": dict(
        name_long="OOBB Geometry Primitives: Rounded Rectangle (Rounded Edges)",
        description="Rounded rectangle with rounded top and bottom edges (sphere-swept corners) wrapped in a rotation object.",
        category="OOBB Geometry Primitives",
        shape_aliases=["rounded_rectangle_rounded"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("size",            "Overall [x,y,z] dimensions in mm.",         "list",   "[20,10,5]"),
            _v("radius",          "Corner radius of the base shape.",           "number", 5),
            _v("radius_rounded",  "Rounding radius for top/bottom edges.",      "number", 2.5),
            EXTRA_VAR, *ROT_VARS,
        ],
    ),
    "oobb_screw": dict(
        name_long="OOBB Geometry Primitives: Screw",
        description="Screw cutout (socket_cap, countersunk, or self_tapping) with optional through-hole, nut pocket, overhang, and clearance.",
        category="OOBB Geometry Primitives",
        shape_aliases=["screw"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("radius_name",  "Named radius key, e.g. m3, m6.",                 "string", '"m3"'),
            _v("style",        "Screw head style: socket_cap, countersunk, self_tapping.", "string", '"socket_cap"'),
            _v("depth",        "Shaft hole depth in mm.",                         "number", 250),
            _v("zz",           "Z anchor: none, top, bottom.",                    "string", '"none"'),
            _v("hole",         "Include a through shaft hole.",                    "bool",   True),
            _v("clearance",    "Clearance extension sides: top, bottom.",         "string", '""'),
            _v("nut_include",  "Include a nut pocket.",                            "bool",   False),
            _v("overhang",     "Add overhang geometry.",                           "bool",   True),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_screw_countersunk": dict(
        name_long="OOBB Geometry Primitives: Countersunk Screw",
        description="Countersunk screw cutout; wrapper over oobb_screw with style='countersunk' pre-set.",
        category="OOBB Geometry Primitives",
        shape_aliases=["screw_countersunk"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("radius_name", "Named radius key, e.g. m3, m6.", "string", '"m3"'),
            _v("depth",       "Shaft hole depth in mm.",         "number", 250),
            _v("zz",          "Z anchor: none, top, bottom.",    "string", '"none"'),
            _v("hole",        "Include a through shaft hole.",   "bool",   True),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_screw_self_tapping": dict(
        name_long="OOBB Geometry Primitives: Self-Tapping Screw",
        description="Self-tapping screw cutout; wrapper over oobb_screw with style='self_tapping' pre-set.",
        category="OOBB Geometry Primitives",
        shape_aliases=["screw_self_tapping"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("radius_name", "Named radius key, e.g. m3, m6.", "string", '"m3"'),
            _v("depth",       "Shaft hole depth in mm.",         "number", 250),
            _v("zz",          "Z anchor: none, top, bottom.",    "string", '"none"'),
            _v("hole",        "Include a through shaft hole.",   "bool",   True),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_screw_socket_cap": dict(
        name_long="OOBB Geometry Primitives: Socket Cap Screw",
        description="Socket-cap screw cutout; wrapper over oobb_screw with style='socket_cap' pre-set.",
        category="OOBB Geometry Primitives",
        shape_aliases=["screw_socket_cap"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("radius_name", "Named radius key, e.g. m3, m6.", "string", '"m3"'),
            _v("depth",       "Shaft hole depth in mm.",         "number", 250),
            _v("zz",          "Z anchor: none, top, bottom.",    "string", '"none"'),
            _v("hole",        "Include a through shaft hole.",   "bool",   True),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_slice": dict(
        name_long="OOBB Geometry Primitives: Slice",
        description="Large cube slice used to clip/intersect geometry.",
        category="OOBB Geometry Primitives",
        shape_aliases=["slice"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR,
            _v("size", "[x,y,z] dimensions of the slice cube in mm.", "list", "[500,500,500]"),
            _v("zz",   "Z anchor: bottom or top.",                    "string", '"bottom"'),
            MODE_VAR,
        ],
    ),
    "oobb_slot": dict(
        name_long="OOBB Geometry Primitives: Slot",
        description="Slot (two-ended rounded cutout) with rotation-object support, mode filtering, and named/explicit radius.",
        category="OOBB Geometry Primitives",
        shape_aliases=["slot"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("depth",       "Slot depth in mm.",                  "number", 250),
            _v("radius",      "Slot end-cap radius in mm.",         "number", '""'),
            _v("radius_name", "Named radius for mode-aware lookup.","string", '""'),
            _v("zz",          "Z anchor: middle, bottom, top.",     "string", '"middle"'),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_sphere": dict(
        name_long="OOBB Geometry Primitives: Sphere",
        description="Sphere (optionally ellipsoidal via radius_1/radius_2 scale) with z-anchor support.",
        category="OOBB Geometry Primitives",
        shape_aliases=["sphere"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR,
            _v("radius",   "Sphere radius in mm.",               "number", 10),
            _v("radius_1", "Base radius for ellipsoid scaling.", "number", "(optional)"),
            _v("radius_2", "Z-scale radius for ellipsoid.",      "number", "(optional)"),
            _v("zz",       "Z anchor: bottom, top, middle.",     "string", '"bottom"'),
        ],
    ),
    "oobb_tube": dict(
        name_long="OOBB Geometry Primitives: Tube",
        description="Tube cutout (hollow cylinder) across all render modes, with named/explicit radius and rotation support.",
        category="OOBB Geometry Primitives",
        shape_aliases=["tube"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("r",              "Outer radius in mm.",                 "number", '""'),
            _v("radius_name",    "Named radius for mode-aware lookup.", "string", '""'),
            _v("wall_thickness", "Wall thickness for inner cylinder.", "number", 0.5),
            _v("depth",          "Tube height in mm.",                 "number", 250),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    "oobb_tube_new": dict(
        name_long="OOBB Geometry Primitives: Tube (New)",
        description="Tube cutout with updated rendering pipeline; identical interface to oobb_tube.",
        category="OOBB Geometry Primitives",
        shape_aliases=["tube_new"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("r",              "Outer radius in mm.",                 "number", '""'),
            _v("radius_name",    "Named radius for mode-aware lookup.", "string", '""'),
            _v("wall_thickness", "Wall thickness for inner cylinder.", "number", 0.5),
            _v("depth",          "Tube height in mm.",                 "number", 250),
            MODE_VAR, *ROT_VARS,
        ],
    ),
    # ── oobb wire cutouts ────────────────────────────────────────────────────
    "oobb_wire_base": dict(
        name_long="OOBB Wire Cutouts: Wire Base",
        description="Base wire cutout delegate; forwards all kwargs to the legacy wire builder.",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_base"],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "oobb_wire_basic": dict(
        name_long="OOBB Wire Cutouts: Basic 3-Pin Wire",
        description="3-pin polarized wire cutout; wraps oobb_wire_cutout with num_pins=3 and polarized=True.",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_basic"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("width",   "Wire connector footprint width in grid units.",  "number", 2),
            _v("height",  "Wire connector footprint height in grid units.", "number", 2),
            _v("through", "Cutout goes fully through the material.",        "bool",   False),
            MODE_VAR,
        ],
    ),
    "oobb_wire_cutout": dict(
        name_long="OOBB Wire Cutouts: Wire Cutout (Base)",
        description="Base wire connector cutout geometry for JST-style connectors; configurable pin count and polarization.",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_cutout"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("num_pins",   "Number of connector pins.",                    "number", 2),
            _v("polarized",  "Add polarization dot and extra pin slot.",     "bool",   False),
            _v("width",      "Connector footprint width in grid units.",     "number", 2),
            _v("height",     "Connector footprint height in grid units.",    "number", 2),
            _v("through",    "Escape cutout depth is full through.",         "bool",   False),
            MODE_VAR,
        ],
    ),
    "oobb_wire_higher_voltage": dict(
        name_long="OOBB Wire Cutouts: Higher Voltage 2-Pin Wire",
        description="2-pin polarized wire cutout for higher-voltage connections.",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_higher_voltage"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("width",   "Connector footprint width in grid units.",  "number", 2),
            _v("height",  "Connector footprint height in grid units.", "number", 2),
            _v("through", "Cutout goes fully through the material.",   "bool",   False),
            MODE_VAR,
        ],
    ),
    "oobb_wire_i2c": dict(
        name_long="OOBB Wire Cutouts: I2C 4-Pin Wire",
        description="4-pin polarized wire cutout for I2C connections.",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_i2c"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("width",   "Connector footprint width in grid units.",  "number", 2),
            _v("height",  "Connector footprint height in grid units.", "number", 2),
            _v("through", "Cutout goes fully through the material.",   "bool",   False),
            MODE_VAR,
        ],
    ),
    "oobb_wire_motor": dict(
        name_long="OOBB Wire Cutouts: Motor 2-Pin Wire",
        description="2-pin non-polarized wire cutout for motor connections.",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_motor"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("width",   "Connector footprint width in grid units.",  "number", 2),
            _v("height",  "Connector footprint height in grid units.", "number", 2),
            _v("through", "Cutout goes fully through the material.",   "bool",   False),
            MODE_VAR,
        ],
    ),
    "oobb_wire_motor_stepper": dict(
        name_long="OOBB Wire Cutouts: Stepper Motor 4-Pin Wire",
        description="4-pin non-polarized wire cutout for stepper motor connections.",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_motor_stepper"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("width",   "Connector footprint width in grid units.",  "number", 2),
            _v("height",  "Connector footprint height in grid units.", "number", 2),
            _v("through", "Cutout goes fully through the material.",   "bool",   False),
            MODE_VAR,
        ],
    ),
    "oobb_wire_spacer": dict(
        name_long="OOBB Wire Cutouts: Wire Spacer",
        description="Standard-length wire spacer plate (length=23 mm).",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_spacer"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("thickness", "Plate thickness used to offset z position.", "number", 1),
        ],
    ),
    "oobb_wire_spacer_base": dict(
        name_long="OOBB Wire Cutouts: Wire Spacer Base",
        description="Base rounded-rectangle spacer plate geometry used by all wire spacer variants.",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_spacer_base"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("length_spacer", "Length of the rounded-rectangle spacer plate.", "number", 23),
            _v("pos_spacer",    "Positional offset applied to the spacer plate.", "list",  "[-1.5,0,0]"),
            _v("thickness",     "Plate thickness (z size) and z-offset adjustment.", "number", 1),
        ],
    ),
    "oobb_wire_spacer_long": dict(
        name_long="OOBB Wire Cutouts: Wire Spacer Long",
        description="Longer wire spacer plate (length=29 mm).",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_spacer_long"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("thickness", "Plate thickness used to offset z position.", "number", 1),
        ],
    ),
    "oobb_wire_spacer_u": dict(
        name_long="OOBB Wire Cutouts: Wire Spacer U",
        description="Extra-long U-shaped wire spacer plate (length=40 mm).",
        category="OOBB Wire Cutouts",
        shape_aliases=["wire_spacer_u"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("thickness", "Plate thickness used to offset z position.", "number", 1),
        ],
    ),
    "oobb_zip_tie_clearance_small": dict(
        name_long="OOBB Wire Cutouts: Small Zip-Tie Clearance",
        description="Small zip-tie clearance cutout: two M3 holes spaced 6 mm apart and a rectangular slot.",
        category="OOBB Wire Cutouts",
        shape_aliases=["zip_tie_clearance_small"],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR, TYPE_VAR,
            _v("wall_thickness", "Wall thickness context (read but not yet used).", "number", 2),
        ],
    ),
    # ── Part sets ────────────────────────────────────────────────────────────
    "bearings": dict(
        name_long="Part Sets: Bearings",
        description="Builds a bearing solid+hole cylinder pair from named bearing lookup tables.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[
            _v("bearing_name", "Bearing identifier, e.g. 608, 6704.", "string", "(required)"),
        ],
    ),
    "bearing_circles": dict(
        name_long="Part Sets: Bearing Circles",
        description="Delegates to the legacy get_bearing_circle function for bearing circle geometry.",
        category="Part Sets",
        shape_aliases=["bcs"],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "bearing_plates": dict(
        name_long="Part Sets: Bearing Plates",
        description="Delegates to get_bearing_plate for bearing plate geometry.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "circles": dict(
        name_long="Part Sets: Circles",
        description="Dispatches to a get_plate_<extra> function or falls back to get_circle_base based on the extra field.",
        category="Part Sets",
        shape_aliases=["circle"],
        returns="List of part definition dicts.",
        variables=[
            EXTRA_VAR,
            _v("thickness", "Plate depth used to compute z-position offsets.", "number", 3),
            _v("zz",        "Vertical anchor: bottom, middle, top.",           "string", '"bottom"'),
            POS_VAR,
        ],
    ),
    "gears": dict(
        name_long="Part Sets: Gears",
        description="Delegates to oobb_get_items_oobb.get_gear for gear geometry.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "holders": dict(
        name_long="Part Sets: Holders",
        description="Delegates to oobb_get_items_oobb.get_holder for electronic/mechanical holder geometry.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "jacks": dict(
        name_long="Part Sets: Jacks",
        description="Delegates to the legacy get_jack function for jack geometry.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "jigs": dict(
        name_long="Part Sets: Jigs",
        description="Delegates to the legacy get_jig function; extra field selects the sub-type.",
        category="Part Sets",
        shape_aliases=["jgs"],
        returns="List of part definition dicts.",
        variables=[
            _v("extra", "Selects the jig sub-type function.", "string", "(required)"),
        ],
    ),
    "mounting_plates": dict(
        name_long="Part Sets: Mounting Plates",
        description="Delegates to the legacy get_mounting_plate function.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "nuts": dict(
        name_long="Part Sets: Nuts",
        description="Builds a nut solid+through-hole pair using named radius lookup tables.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[
            _v("radius_name", "Named radius key, e.g. m3, m6.", "string", "(required)"),
        ],
    ),
    "others": dict(
        name_long="Part Sets: Others",
        description="Dispatches to get_other_<extra> in oobb_get_items_oobb_other; requires a non-empty extra field.",
        category="Part Sets",
        shape_aliases=["ots"],
        returns="List of part definition dicts.",
        variables=[
            _v("extra", "Selects which get_other_* function to call.", "string", "(required)"),
        ],
    ),
    "plates": dict(
        name_long="Part Sets: Plates",
        description="Dispatches to get_plate_<extra> or falls back to get_plate_base for rectangular plates.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[
            EXTRA_VAR,
        ],
    ),
    "pulleys": dict(
        name_long="Part Sets: Pulleys",
        description="Delegates to oobb_get_items_oobb.get_pulley_gt2 for GT2 pulley geometry.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "screws": dict(
        name_long="Part Sets: Screws",
        description="Part set for screw items; see individual screw variant components for geometry.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "shafts": dict(
        name_long="Part Sets: Shafts",
        description="Delegates to the legacy get_shaft function for shaft geometry.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "shaft_couplers": dict(
        name_long="Part Sets: Shaft Couplers",
        description="Delegates to the legacy get_shaft_coupler function.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "smd_magazines": dict(
        name_long="Part Sets: SMD Magazines",
        description="Delegates to the legacy get_smd_magazine function.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "soldering_jigs": dict(
        name_long="Part Sets: Soldering Jigs",
        description="Delegates to the legacy get_soldering_jig function.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "tests": dict(
        name_long="Part Sets: Tests",
        description="Dispatches to get_test_<extra> in oobb_get_items_test; requires a non-empty extra field.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[
            _v("extra", "Selects which get_test_* function to call.", "string", "(required)"),
        ],
    ),
    "tool_holders": dict(
        name_long="Part Sets: Tool Holders",
        description="Delegates to the legacy get_tool_holder function.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "trays": dict(
        name_long="Part Sets: Trays",
        description="Delegates to the legacy get_tray function.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "wheels": dict(
        name_long="Part Sets: Wheels",
        description="Dispatches to get_wheel_<extra> or get_wheel; extra list is joined with underscores.",
        category="Part Sets",
        shape_aliases=["whl"],
        returns="List of part definition dicts.",
        variables=[
            _v("extra", "Wheel sub-type selector; empty string calls get_wheel.", "string", '""'),
        ],
    ),
    "wires": dict(
        name_long="Part Sets: Wires",
        description="Dispatches to get_wire_<extra> in oobb_get_items_oobb_wire; requires non-empty extra.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[
            _v("extra", "Wire sub-type selector (joined with _ if list).", "string", "(required)"),
        ],
    ),
    "ziptie_holders": dict(
        name_long="Part Sets: Ziptie Holders",
        description="Delegates to the legacy get_ziptie_holder function.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    "buntings": dict(
        name_long="Part Sets: Buntings",
        description="Delegates to the legacy get_bunting_alphabet function.",
        category="Part Sets",
        shape_aliases=[],
        returns="List of part definition dicts.",
        variables=[],
    ),
    # ── Plates ───────────────────────────────────────────────────────────────
    "plate_base": dict(
        name_long="Plates: Base Plate",
        description="Base rectangular plate with standard OOBB holes and optional extras (gorm, slip_center, slip_end, slip_corner).",
        category="Plates",
        shape_aliases=["plate_base"],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",      "Plate width in OOBB units.",          "number", 1),
            _v("height",     "Plate height in OOBB units.",         "number", 1),
            _v("thickness",  "Plate depth in mm.",                  "number", 3),
            _v("size",       "OOBB size variant.",                  "string", '"oobb"'),
            POS_VAR, EXTRA_VAR,
            _v("holes",      "Include hole geometry.",              "bool",   True),
            _v("both_holes", "Add holes on both faces.",            "bool",   True),
        ],
    ),
    "plate_dict": dict(
        name_long="Plates: Plate (Dict)",
        description="Delegates to shared get_plate_dict helper in oobb_arch.",
        category="Plates",
        shape_aliases=["plate_dict"],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "plate_hole_dict": dict(
        name_long="Plates: Plate Hole Dict",
        description="Delegates to shared get_plate_hole_dict helper in oobb_arch.",
        category="Plates",
        shape_aliases=["plate_hole_dict"],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "plate_l": dict(
        name_long="Plates: L-Shaped Plate",
        description="L-shaped plate geometry; delegates to oobb_get_items_oobb.get_plate_l.",
        category="Plates",
        shape_aliases=["plate_l"],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "plate_label": dict(
        name_long="Plates: Label Plate",
        description="Label plate that composes a sub-plate with right-side holes.",
        category="Plates",
        shape_aliases=["plate_label"],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",      "Plate width in OOBB units.",   "number", 1),
            _v("height",     "Plate height in OOBB units.",  "number", 1),
            _v("thickness",  "Plate depth in mm.",           "number", 3),
            POS_VAR, EXTRA_VAR,
            _v("holes",      "Hole presence flag.",          "bool",   True),
            _v("both_holes", "Both-holes flag.",             "bool",   True),
        ],
    ),
    "plate_ninety_degree": dict(
        name_long="Plates: 90-Degree Plate",
        description="90-degree plate with multi-axis M6/M3 hole patterns.",
        category="Plates",
        shape_aliases=["plate_ninety_degree"],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",      "Plate width in OOBB units.",   "number", 1),
            _v("height",     "Plate height in OOBB units.",  "number", 1),
            _v("thickness",  "Plate depth in mm.",           "number", 3),
            POS_VAR, EXTRA_VAR,
            _v("holes",      "Generate the hole grid.",      "bool",   True),
            _v("both_holes", "Add holes on both faces.",     "bool",   True),
        ],
    ),
    "plate_nut_dict": dict(
        name_long="Plates: Plate Nut Dict",
        description="Delegates to oobb_get_items_oobb_wire.get_plate_nut_dict.",
        category="Plates",
        shape_aliases=["plate_nut_dict"],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "plate_old": dict(
        name_long="Plates: Plate (Legacy)",
        description="Legacy plate builder; delegates to get_plate_old.",
        category="Plates",
        shape_aliases=["plate_old"],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "plate_t": dict(
        name_long="Plates: T-Shaped Plate",
        description="T-shaped plate; delegates to oobb_get_items_oobb.get_plate_t.",
        category="Plates",
        shape_aliases=["plate_t"],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "plate_u": dict(
        name_long="Plates: U-Shaped Plate",
        description="U-shaped plate; delegates to oobb_get_items_oobb.get_plate_u.",
        category="Plates",
        shape_aliases=["plate_u"],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "plate_u_double": dict(
        name_long="Plates: Double-U Plate",
        description="Double-U shaped plate; delegates to oobb_get_items_oobb.get_plate_u_double.",
        category="Plates",
        shape_aliases=["plate_u_double"],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    # ── Bearing plates ───────────────────────────────────────────────────────
    "bearing_plate_connecting_screw_center": dict(
        name_long="Bearing Plates: Connecting Screw Center",
        description="Adds countersunk connecting screws at the center zone of a bearing plate.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("thickness", "Plate thickness in mm.", "number", 3),
            POS_VAR,
            _v("bearing",   "Bearing type identifier, e.g. 6704.", "string", '"6704"'),
            _v("shaft",     "Shaft type identifier, e.g. m6.",     "string", '"m6"'),
        ],
    ),
    "bearing_plate_connecting_screw_perimeter": dict(
        name_long="Bearing Plates: Connecting Screw Perimeter",
        description="Adds countersunk connecting screws at the perimeter of a bearing plate.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("thickness", "Plate thickness in mm.", "number", 3),
            POS_VAR,
            _v("bearing",   "Bearing type identifier.", "string", '"6704"'),
            EXTRA_VAR,
        ],
    ),
    "bearing_plate_hole_center": dict(
        name_long="Bearing Plates: Hole Center",
        description="Adds center-zone fastener holes (M3 holes/nuts or circle pattern) matching the bearing type.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("shaft",     "Shaft type identifier.", "string", '"m6"'),
            EXTRA_VAR,
            _v("thickness", "Plate thickness in mm.", "number", 3),
            _v("bearing",   "Bearing type identifier.", "string", '"6704"'),
        ],
    ),
    "bearing_plate_hole_perimeter": dict(
        name_long="Bearing Plates: Hole Perimeter",
        description="Adds perimeter fastener holes to a bearing plate; routes to base or shifted variant based on extra.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",     "Plate width in OOBB units.",  "number", 1),
            _v("height",    "Plate height in OOBB units.", "number", 1),
            _v("thickness", "Plate thickness in mm.",      "number", 3),
            _v("size",      "OOBB grid size prefix.",      "string", '"oobb"'),
            POS_VAR,
            _v("shaft",     "Shaft type identifier.",      "string", '"m6"'),
            EXTRA_VAR,
            _v("bearing",   "Bearing type identifier.",    "string", '"6704"'),
        ],
    ),
    "bearing_plate_hole_perimeter_base": dict(
        name_long="Bearing Plates: Hole Perimeter Base",
        description="Adds standard perimeter fastener holes (miss-middle pattern) to a bearing plate.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",     "Plate width in OOBB units.",  "number", 1),
            _v("height",    "Plate height in OOBB units.", "number", 1),
            _v("thickness", "Plate thickness in mm.",      "number", 3),
            _v("size",      "OOBB grid size prefix.",      "string", '"oobb"'),
            POS_VAR,
            _v("shaft",     "Shaft type identifier.",      "string", '"m6"'),
            EXTRA_VAR,
            _v("bearing",   "Bearing type identifier.",    "string", '"6704"'),
        ],
    ),
    "bearing_plate_hole_perimeter_shifted": dict(
        name_long="Bearing Plates: Hole Perimeter Shifted",
        description="Adds perimeter fastener holes with a shifted plate origin.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",     "Plate width in OOBB units.",        "number", 1),
            _v("height",    "Plate height in OOBB units.",       "number", 1),
            _v("thickness", "Plate thickness in mm.",            "number", 3),
            POS_VAR,
            _v("pos_plate", "Shifted plate origin position.",    "list",   "[0,0,0]"),
            _v("shaft",     "Shaft type identifier.",            "string", '"m6"'),
            EXTRA_VAR,
            _v("bearing",   "Bearing type identifier.",          "string", '"6704"'),
        ],
    ),
    "bearing_plate_hole_shaft": dict(
        name_long="Bearing Plates: Shaft Hole",
        description="Cuts the central shaft hole in a bearing plate; shape varies by shaft type.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",     "Plate width in OOBB units.",  "number", 1),
            _v("height",    "Plate height in OOBB units.", "number", 1),
            _v("thickness", "Plate thickness in mm.",      "number", 3),
            POS_VAR,
            _v("shaft",     "Shaft type: m6, coupler_flanged, motor_tt_01, motor_servo_standard_01, etc.", "string", '"m6"'),
            EXTRA_VAR,
            _v("bearing",   "Bearing type identifier.",    "string", '"608"'),
        ],
    ),
    "bearing_plate_jack": dict(
        name_long="Bearing Plates: Jack",
        description="Legacy combined bearing-plate-and-jack assembly component.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "bearing_plate_jack_basic": dict(
        name_long="Bearing Plates: Jack Basic",
        description="Legacy bearing-plate with a basic jack (simpler variant, includes 3D-print slice logic).",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "bearing_plate_old": dict(
        name_long="Bearing Plates: Legacy Bearing Plate",
        description="Legacy monolithic bearing plate builder with full hole/shaft/bearing patterns in one call.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("shaft",        "Shaft type identifier.",              "string", '"m6"'),
            _v("radius_name",  "Hole radius name for perimeter holes.","string", '"m6"'),
            _v("width",        "Plate width in OOBB units.",          "number", '""'),
            _v("height",       "Plate height in OOBB units.",         "number", '""'),
            _v("thickness",    "Plate thickness in mm.",              "number", '""'),
            _v("bearing_type", "Bearing type identifier.",            "string", '"608"'),
            EXTRA_VAR, POS_VAR,
        ],
    ),
    "bearing_plate_plate": dict(
        name_long="Bearing Plates: Plate Body",
        description="Generates the solid plate body of a bearing plate (rectangular or cylindrical) sized to the bearing OD.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",     "Plate width in OOBB units.",  "number", 1),
            _v("height",    "Plate height in OOBB units.", "number", 1),
            _v("thickness", "Plate thickness in mm.",      "number", 3),
            POS_VAR,
            _v("shaft",     "Shaft type.",                 "string", '"m6"'),
            _v("bearing",   "Bearing type identifier.",    "string", '"608"'),
            EXTRA_VAR,
        ],
    ),
    "bearing_plate_shim": dict(
        name_long="Bearing Plates: Shim",
        description="Thin shim ring sized to fit between a bearing's OD catch and ID.",
        category="Bearing Plates",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("bearing_type", "Bearing type identifier.", "string", '"6803"'),
            _v("thickness",    "Shim thickness in mm.",    "number", 3),
        ],
    ),
    # ── Other product components ─────────────────────────────────────────────
    "bearing_wheel": dict(
        name_long="Other: Bearing Wheel",
        description="Circular wheel with o-ring groove, bearing cutout, and connecting screws.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("oring_type",   "O-ring size identifier (drives wheel diameter).", "string", '"327"'),
            _v("thickness",    "Wheel thickness in mm (9=single, 15=dual bearing).","number", 9),
            POS_VAR,
            _v("bearing_type", "Bearing type for the central cutout.",             "string", '"606"'),
        ],
    ),
    "bolt": dict(
        name_long="Fasteners: Bolt",
        description="Generates a hex-head bolt with specified size and length.",
        category="Fasteners",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("radius_name", "Bolt size designation, e.g. m5, m6.", "string", '"m6"'),
            _v("depth",       "Bolt length in mm.",                   "number", 20),
        ],
    ),
    "bracket_2020_aluminium_extrusion": dict(
        name_long="Other: 2020 Aluminium Extrusion Bracket",
        description="Bracket plate with M6 and intermediate holes for attaching to 2020 aluminium extrusion.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",     "Bracket width in OOBB units.",  "number", 10),
            _v("height",    "Bracket height in OOBB units.", "number", 10),
            _v("thickness", "Plate thickness in mm.",        "number", 3),
        ],
    ),
    "circle_base": dict(
        name_long="Circles: Circle Base",
        description="Base circular geometry builder with optional shaft hole, perimeter holes, and doughnut cutout.",
        category="Circles",
        shape_aliases=["circle_base"],
        returns="List of geometry component dicts.",
        variables=[
            _v("diameter",   "Circle diameter in OOBB units.",                    "number", 1),
            _v("thickness",  "Circle thickness in mm.",                           "number", 3),
            _v("size",       "OOBB grid size prefix.",                            "string", '"oobb"'),
            POS_VAR, EXTRA_VAR,
            _v("shaft",      "Shaft type; suppresses middle hole when set.",      "string", '""'),
            _v("holes",      "Add perimeter holes.",                              "bool",   True),
            _v("both_holes", "Add both oobb and oobe holes.",                     "bool",   True),
        ],
    ),
    "circle_captive": dict(
        name_long="Circles: Circle Captive",
        description="Circular geometry with a captive shaft hole and press-fit M3/M6 nuts around the perimeter.",
        category="Circles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("shaft",     "Shaft type used to cut the captive hole.", "string", '""'),
            _v("diameter",  "Circle diameter in OOBB units.",          "number", 1),
            _v("thickness", "Circle thickness in mm.",                 "number", 3),
            _v("holes",     "Add perimeter holes.",                    "bool",   True),
        ],
    ),
    "circle_old_1": dict(
        name_long="Circles: Circle (Legacy)",
        description="Legacy circular geometry builder with optional holes, both-holes, extra nut, and center-hole patterns.",
        category="Circles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("diameter",              "Circle diameter in OOBB units.", "number", 1),
            _v("thickness",             "Circle thickness in mm.",        "number", 3),
            _v("holes",                 "Add standard hole patterns.",    "bool",   True),
            _v("both_holes",            "Also add oobe (intermediate) holes.", "bool", False),
            _v("exclude_d3_holes",      "Skip diagonal 45° holes on diameter-3 circles.", "bool", False),
            _v("exclude_center_holes",  "Skip center-region holes.",      "bool",   False),
            EXTRA_VAR,
        ],
    ),
    "ci_holes_center": dict(
        name_long="Circles: Intercardinal Holes Center",
        description="Adds M3 holes and/or slots at the center intercardinal positions of a circular part.",
        category="Circles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            POS_VAR,
            _v("slots",   "Add slot cutouts on the X axis.",              "bool", True),
            _v("holes",   "Add hole cutouts on the Y axis.",              "bool", True),
            _v("inserts", "Add threaded insert pockets instead of holes.","bool", False),
        ],
    ),
    "gear_double_stack": dict(
        name_long="Gears: Double Stack Gear",
        description="Stacks two gear layers (each half the total thickness) with per-layer diameter and extra settings.",
        category="Gears",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("diameter",  "List of two diameters (one per gear layer) in OOBB units.", "list", 1),
            _v("thickness", "Total gear stack thickness in mm (split equally).",          "number", 3),
            POS_VAR, EXTRA_VAR,
            _v("shaft",     "Shaft type.",                                                "string", '"m6"'),
            _v("holes",     "Add holes to each layer.",                                   "bool",   True),
        ],
    ),
    "gridfinity_base_tile": dict(
        name_long="Gridfinity: Base Tile",
        description="Returns the raw OpenSCAD source for a Gridfinity base tile.",
        category="Gridfinity",
        shape_aliases=["gridfinity_base_tile"],
        returns="SCAD source string.",
        variables=[],
    ),
    "jack_basic": dict(
        name_long="Other: Jack Basic",
        description="Legacy jack component — a plate with an extending cube tab and M6 bolt holes for wall-mounting.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",     "Width in OOBB units.",   "number", 2),
            _v("height",    "Height in OOBB units.",  "number", 2),
            _v("thickness", "Plate thickness in mm.", "number", 3),
        ],
    ),
    "jig_screw_sorter_m3_03_03": dict(
        name_long="Jigs: M3 Screw Sorter (3×3)",
        description="Tray jig with a grid of M3 countersunk screw sorter holes, 3×3 OOBB tray base.",
        category="Jigs",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "jig_tray_03_03": dict(
        name_long="Jigs: Tray Jig (3×3)",
        description="3×3 OOBB tray jig with optional screw holes for assembly alignment.",
        category="Jigs",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "mounting_plate_generic": dict(
        name_long="Holders: Generic Mounting Plate",
        description="Generic configurable mounting plate with OOBB hole patterns.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "mounting_plate_side": dict(
        name_long="Holders: Side Mounting Plate",
        description="Side-oriented mounting plate for OOBB assemblies.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "mounting_plate_top": dict(
        name_long="Holders: Top Mounting Plate",
        description="Top-oriented mounting plate for OOBB assemblies.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "mounting_plate_u": dict(
        name_long="Holders: U-Shape Mounting Plate",
        description="U-shaped mounting plate for OOBB assemblies.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "nut_m3": dict(
        name_long="Fasteners: M3 Nut",
        description="M3 nut pocket with optional through-hole; wrapper over oobb_nut with radius_name='m3'.",
        category="Fasteners",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR, TYPE_VAR, _v("hole", "Include a through-hole.", "bool", False)],
    ),
    # ── Holders (auto-generated scaffolds) ────────────────────────────────────
    "holder_electronic_battery_box_aa_battery_4_cell": dict(
        name_long="Holders: AA Battery Box (4-Cell)",
        description="Holder for a 4-cell AA battery box.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronic_button_11_mm_panel_mount": dict(
        name_long="Holders: 11mm Panel Mount Button",
        description="Holder for an 11 mm panel-mount push-button.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronic_button_11_mm_panel_mount_x4": dict(
        name_long="Holders: 11mm Panel Mount Button ×4",
        description="Holder for four 11 mm panel-mount push-buttons.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronic_potentiometer_17_mm": dict(
        name_long="Holders: 17mm Potentiometer",
        description="Holder for a 17 mm potentiometer.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronic_potentiometer_stick_single_axis_16_mm": dict(
        name_long="Holders: 16mm Single-Axis Joystick",
        description="Holder for a single-axis 16 mm joystick-style potentiometer.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronic_potentiometer_stick_single_axis_16_mm_arm": dict(
        name_long="Holders: 16mm Single-Axis Joystick Arm",
        description="Arm sub-part for the single-axis 16 mm joystick-style potentiometer holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronics_base_03_03": dict(
        name_long="Holders: Electronics Base 3×3",
        description="3×3-unit electronics base plate holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronics_mcu_atmega328_shennie": dict(
        name_long="Holders: ATmega328 Shennie MCU",
        description="Holder for an ATmega328 'Shennie' MCU board.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronics_microswitch_standard": dict(
        name_long="Holders: Standard Microswitch",
        description="Holder for a standard microswitch.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronics_potentiometer_17": dict(
        name_long="Holders: 17mm Potentiometer (Legacy)",
        description="Legacy holder for a 17 mm potentiometer.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronics_pushbutton_11": dict(
        name_long="Holders: 11mm Push-Button (Legacy)",
        description="Legacy holder for an 11 mm push-button.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_electronics_pushbutton_11_x4": dict(
        name_long="Holders: 11mm Push-Button ×4 (Legacy)",
        description="Legacy holder for four 11 mm push-buttons.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_fan_120_mm": dict(
        name_long="Holders: 120mm Fan",
        description="Holder for a 120 mm fan.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_building_block_large_01": dict(
        name_long="Holders: Large Building Block Motor",
        description="Large building-block motor holder (revision 01).",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_building_block_large_01_bottom": dict(
        name_long="Holders: Large Building Block Motor (Bottom)",
        description="Bottom sub-part of the large building-block motor holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_building_block_small_01_bottom": dict(
        name_long="Holders: Small Building Block Motor (Bottom)",
        description="Bottom sub-part of the small building-block motor holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_gearmotor_01": dict(
        name_long="Holders: Gearmotor",
        description="Gearmotor holder (revision 01).",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_gearmotor_01_old_01": dict(
        name_long="Holders: Gearmotor (Legacy 01)",
        description="First legacy revision of the gearmotor holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_gearmotor_01_old_02": dict(
        name_long="Holders: Gearmotor (Legacy 02)",
        description="Second legacy revision of the gearmotor holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_generic": dict(
        name_long="Holders: Generic Motor",
        description="Generic configurable motor holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_micro_01": dict(
        name_long="Holders: Micro Servo Motor",
        description="Micro servo motor holder (revision 01).",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01": dict(
        name_long="Holders: Standard Servo Motor",
        description="Standard servo motor holder (revision 01).",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01_all_debug": dict(
        name_long="Holders: Standard Servo Motor (All Debug)",
        description="All-parts debug assembly of the standard servo holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01_all_print": dict(
        name_long="Holders: Standard Servo Motor (All Print)",
        description="All-parts print assembly of the standard servo holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01_base": dict(
        name_long="Holders: Standard Servo Motor (Base)",
        description="Base sub-part of the standard servo holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01_base_extra_variables": dict(
        name_long="Holders: Standard Servo Motor (Base Extra Variables)",
        description="Base sub-part of the standard servo holder with extra configurable variables.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01_bottom": dict(
        name_long="Holders: Standard Servo Motor (Bottom)",
        description="Bottom sub-part of the standard servo holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01_bottom_old_1": dict(
        name_long="Holders: Standard Servo Motor Bottom (Legacy)",
        description="Legacy first-revision bottom of the standard servo holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01_old": dict(
        name_long="Holders: Standard Servo Motor (Legacy)",
        description="Legacy-revision standard servo holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01_old_1": dict(
        name_long="Holders: Standard Servo Motor (Legacy Revision 1)",
        description="Revision old_1 of the standard servo holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_servo_standard_01_top": dict(
        name_long="Holders: Standard Servo Motor (Top)",
        description="Top sub-part of the standard servo holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_stepper_motor_nema_17_both": dict(
        name_long="Holders: NEMA-17 Stepper Motor (Both Sides)",
        description="Combined both-side NEMA-17 stepper motor holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_stepper_motor_nema_17_flat": dict(
        name_long="Holders: NEMA-17 Stepper Motor (Flat, Legacy)",
        description="Legacy flat-mount NEMA-17 stepper motor holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_stepper_motor_nema_17_jack": dict(
        name_long="Holders: NEMA-17 Stepper Motor (Jack)",
        description="Jack-style NEMA-17 stepper motor holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_stepper_nema_17_flat": dict(
        name_long="Holders: NEMA-17 Stepper Motor (Flat)",
        description="Flat-mount NEMA-17 stepper motor holder (current revision).",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_stepper_nema_17_flat_shifted": dict(
        name_long="Holders: NEMA-17 Stepper Motor (Flat Shifted)",
        description="Shifted flat-mount NEMA-17 stepper motor holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_stepper_nema_17_flat_shifted_spacer_10_mm": dict(
        name_long="Holders: NEMA-17 Stepper Motor (Flat Shifted 10mm Spacer)",
        description="10 mm spacer variant of the shifted flat NEMA-17 holder.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_motor_tt_01": dict(
        name_long="Holders: TT Motor",
        description="TT (yellow) gearmotor holder (revision 01).",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_old": dict(
        name_long="Holders: Generic Holder (Legacy)",
        description="Legacy generic holder base.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "holder_powerbank_anker_323": dict(
        name_long="Holders: Anker 323 Powerbank",
        description="Holder for an Anker 323 power bank.",
        category="Holders",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    # ── Screws (product) ─────────────────────────────────────────────────────
    "screw_countersunk": dict(
        name_long="Fasteners: Countersunk Screw",
        description="Generates a countersunk screw with configurable thread size and depth.",
        category="Fasteners",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("radius_name", "Screw thread size, e.g. m3, m5.", "string", '"m3"'),
            _v("depth",       "Screw length/depth in mm.",        "number", 10),
        ],
    ),
    "screw_self_tapping": dict(
        name_long="Fasteners: Self-Tapping Screw",
        description="Generates a self-tapping screw with configurable thread size and depth.",
        category="Fasteners",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("radius_name", "Screw thread size, e.g. m3, m4.", "string", '"m3"'),
            _v("depth",       "Screw length/depth in mm.",        "number", 10),
        ],
    ),
    "screw_socket_cap": dict(
        name_long="Fasteners: Socket Cap Screw",
        description="Generates a socket head cap screw with configurable thread size and length.",
        category="Fasteners",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("radius_name", "Screw thread size, e.g. m3, m5.", "string", '"m3"'),
            _v("depth",       "Screw length/depth in mm.",        "number", 12),
        ],
    ),
    # ── Other misc ───────────────────────────────────────────────────────────
    "other_bolt_stacker": dict(
        name_long="Other: Bolt Stacker",
        description="Bolt stacker component; delegates to oobb_get_items_oobb_other.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "other_bolt_stacker_cylinder": dict(
        name_long="Other: Bolt Stacker Cylinder",
        description="Cylindrical bolt stacker; delegates to oobb_get_items_oobb_other.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "other_corner_cube": dict(
        name_long="Other: Corner Cube",
        description="Corner cube connector; delegates to oobb_get_items_oobb_other.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "other_corner_cube_basic": dict(
        name_long="Other: Corner Cube Basic",
        description="Basic corner cube connector; delegates to oobb_get_items_oobb_other.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "other_corner_cube_relief": dict(
        name_long="Other: Corner Cube Relief",
        description="Corner cube with relief cuts; delegates to oobb_get_items_oobb_other.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "other_ptfe_tube_holder": dict(
        name_long="Other: PTFE Tube Holder",
        description="PTFE tube holder; delegates to oobb_get_items_oobb_other.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "other_ptfe_tube_holder_ninety_degree": dict(
        name_long="Other: PTFE Tube Holder (90°)",
        description="90-degree PTFE tube holder; delegates to oobb_get_items_oobb_other.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "other_timing_belt_clamp_gt2": dict(
        name_long="Other: GT2 Timing Belt Clamp",
        description="GT2 timing belt clamp; delegates to oobb_get_items_oobb_other.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "pulley_gt2_shield_double": dict(
        name_long="Other: GT2 Double Shield Pulley",
        description="GT2 pulley with double side shields; delegates to oobb_get_items_oobb.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "shaft_center": dict(
        name_long="Shafts: Shaft Center",
        description="Shaft center geometry; delegates to oobb_get_items_oobb.",
        category="Shafts",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "standoff": dict(
        name_long="Fasteners: Standoff",
        description="Generates a standoff with a through-hole for a selected hardware thread size.",
        category="Fasteners",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("radius_name", "Thread size designation, e.g. m3, m5.", "string", '"m3"'),
            _v("depth",       "Standoff length in mm.",                 "number", 10),
        ],
    ),
    "threaded_insert": dict(
        name_long="Fasteners: Threaded Insert",
        description="Generates a heat-set threaded insert profile plus pilot hole geometry.",
        category="Fasteners",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("radius_name", "Thread size designation, e.g. m3, m4.", "string", '"m3"'),
            _v("style",       "Insert style profile identifier.",       "string", '"01"'),
        ],
    ),
    # ── SMD Magazines ────────────────────────────────────────────────────────
    "smd_magazine_joiner": dict(
        name_long="SMD Magazines: Joiner",
        description="SMD magazine joiner connector.",
        category="SMD Magazines",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "smd_magazine_label_holder": dict(
        name_long="SMD Magazines: Label Holder",
        description="SMD magazine label holder.",
        category="SMD Magazines",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "smd_magazine_large": dict(
        name_long="SMD Magazines: Large",
        description="Large SMD magazine tray.",
        category="SMD Magazines",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "smd_magazine_lid": dict(
        name_long="SMD Magazines: Lid",
        description="SMD magazine lid.",
        category="SMD Magazines",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "smd_magazine_old_1": dict(
        name_long="SMD Magazines: Old Revision 1",
        description="Legacy SMD magazine (revision 1).",
        category="SMD Magazines",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "smd_magazine_refiller": dict(
        name_long="SMD Magazines: Refiller",
        description="SMD magazine tape refiller tray.",
        category="SMD Magazines",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "smd_magazine_small": dict(
        name_long="SMD Magazines: Small",
        description="Small SMD magazine tray.",
        category="SMD Magazines",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "smd_magazine_small_old": dict(
        name_long="SMD Magazines: Small (Legacy)",
        description="Legacy small SMD magazine tray.",
        category="SMD Magazines",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    # ── Soldering jigs ───────────────────────────────────────────────────────
    "soldering_jig_electronics_mcu_pi_pico_socket": dict(
        name_long="Jigs: Soldering Jig Pi Pico MCU Socket",
        description="Soldering jig for Pi Pico MCU socket alignment.",
        category="Jigs",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    # ── Tests ────────────────────────────────────────────────────────────────
    "test_gear": dict(
        name_long="Tests: Gear Test Plate",
        description="Parametric gear test plate exploring pressure_angle, clearance, and backlash variations.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("style",       "Gear style variant.",                             "string", '"socket_cap"'),
            POS_VAR,
        ],
    ),
    "test_hole": dict(
        name_long="Tests: Hole Test Plate",
        description="Plate with a grid of progressively sized hole cutouts for fit testing.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("width",     "Plate width in grid units.",          "number", 3),
            _v("height",    "Plate height in grid units.",         "number", 3),
            _v("shaft",     "Starting hole diameter in mm.",       "number", 3),
            _v("bearing",   "Increment step between holes in mm.", "number", 0.5),
            _v("thickness", "Plate thickness in mm.",              "number", 3),
            POS_VAR,
        ],
    ),
    "test_motor_n20_shaft": dict(
        name_long="Tests: N20 Motor Shaft Fit Test",
        description="N20 motor shaft fit-test fixtures across radial clearances.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_motor_tt_01": dict(
        name_long="Tests: TT Motor Fit Test",
        description="TT motor fit-test fixtures for body clearances.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_motor_tt_01_shaft": dict(
        name_long="Tests: TT Motor Shaft Fit Test",
        description="TT motor shaft fit-test fixtures across radial clearances.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_oobb_motor_servo_standard_01": dict(
        name_long="Tests: Standard Servo Orientation Test",
        description="Servo orientation and screw-rotation test fixtures for standard servo profiles.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_oobb_nut": dict(
        name_long="Tests: Nut Test Fixtures",
        description="Nut test fixtures across orientation, depth, and clearance variants.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_oobb_screw": dict(
        name_long="Tests: Screw Test Fixtures",
        description="Screw test fixtures across orientation, nut, and clearance variants.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("style", "Screw style: socket_cap, countersunk, self_tapping.", "string", '"socket_cap"'),
            POS_VAR,
        ],
    ),
    "test_oobb_screw_countersunk": dict(
        name_long="Tests: Countersunk Screw Test",
        description="Countersunk screw test fixtures; style fixed to countersunk.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_oobb_screw_self_tapping": dict(
        name_long="Tests: Self-Tapping Screw Test",
        description="Self-tapping screw test fixtures; style fixed to self_tapping.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_oobb_screw_socket_cap": dict(
        name_long="Tests: Socket Cap Screw Test",
        description="Socket cap screw test fixtures; style fixed to socket_cap.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_oobb_screw_socket_cap_old_1": dict(
        name_long="Tests: Socket Cap Screw Test (Legacy)",
        description="Legacy inline screw socket-cap test fixture.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_oobb_shape_slot": dict(
        name_long="Tests: Slot Shape Test",
        description="Slot shape test fixtures across zz and rotation variants.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_oobb_wire": dict(
        name_long="Tests: Wire Shape Test",
        description="Wire shape test fixtures across all wire styles and rotation variants.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[POS_VAR],
    ),
    "test_rotation": dict(
        name_long="Tests: Rotation Test Fixtures",
        description="Rotation/transform debug fixtures for item orientation verification.",
        category="Tests",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[
            _v("thickness", "Fixture thickness in mm.",                  "number", 3),
            _v("size",      "Grid system: oobb or oobe.",                "string", '"oobb"'),
            _v("holes",     "Include reference holes.",                  "bool",   True),
            POS_VAR,
        ],
    ),
    # ── Tools ────────────────────────────────────────────────────────────────
    "tool_holder_tool_holder_basic": dict(
        name_long="Tools: Basic Tool Holder",
        description="Basic parametric tool holder.",
        category="Tools",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "tool_holder_tool_holder_basic_old_01": dict(
        name_long="Tools: Basic Tool Holder (Legacy)",
        description="Legacy revision of the basic tool holder.",
        category="Tools",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "tool_holder_vertical": dict(
        name_long="Tools: Vertical Tool Holder",
        description="Vertical-orientation tool holder.",
        category="Tools",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    # ── Trays ────────────────────────────────────────────────────────────────
    "tray_lid": dict(
        name_long="Trays: Tray Lid",
        description="Standard tray lid.",
        category="Trays",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "tray_lid_thin": dict(
        name_long="Trays: Thin Tray Lid",
        description="Thin-wall tray lid.",
        category="Trays",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "tray_lid_thin_spin": dict(
        name_long="Trays: Thin Tray Lid (Spin)",
        description="Thin-wall tray lid with spin-lock feature.",
        category="Trays",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "tray_thin": dict(
        name_long="Trays: Thin Tray",
        description="Thin-wall tray body.",
        category="Trays",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "tray_thin_spin": dict(
        name_long="Trays: Thin Tray (Spin)",
        description="Thin-wall tray with spin-lock feature.",
        category="Trays",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "tray_vertical": dict(
        name_long="Trays: Vertical Tray",
        description="Vertically-oriented tray.",
        category="Trays",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    # ── Wire bundles ─────────────────────────────────────────────────────────
    "wire_basic": dict(
        name_long="Wire Bundles: Basic 3-Wire",
        description="3-wire basic bundle routing (basic+basic+basic); delegates to oobb_get_items_oobb_wire.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_basic_basic_basic": dict(
        name_long="Wire Bundles: Basic+Basic+Basic",
        description="Three basic wire bundle routing; delegates to oobb_get_items_oobb_wire.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_basic_basic_basic_basic": dict(
        name_long="Wire Bundles: Basic+Basic+Basic+Basic",
        description="Four basic wire bundle routing; delegates to oobb_get_items_oobb_wire.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_basic_basic_motor": dict(
        name_long="Wire Bundles: Basic+Basic+Motor",
        description="Two basic wires and one motor wire bundle routing.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_higher_voltage": dict(
        name_long="Wire Bundles: Higher Voltage",
        description="Higher-voltage wire bundle routing.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_higher_voltage_basic_basic_motor_stepper": dict(
        name_long="Wire Bundles: Higher Voltage + Stepper Motor",
        description="Higher-voltage wire, two basic wires, and stepper motor wire bundle routing.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_higher_voltage_motor_stepper": dict(
        name_long="Wire Bundles: Higher Voltage + Motor Stepper",
        description="Higher-voltage wire and stepper motor wire bundle routing.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_i2c": dict(
        name_long="Wire Bundles: I2C",
        description="I2C (4-wire) bundle routing.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_motor": dict(
        name_long="Wire Bundles: Motor",
        description="Motor (2-wire) bundle routing.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_motor_basic": dict(
        name_long="Wire Bundles: Motor + Basic",
        description="Motor wire and basic wire bundle routing.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_motor_stepper": dict(
        name_long="Wire Bundles: Stepper Motor",
        description="Stepper motor (4-wire) bundle routing.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_old": dict(
        name_long="Wire Bundles: Legacy Wire",
        description="Legacy wire bundle routing.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_spacer": dict(
        name_long="Wire Bundles: Wire Spacer",
        description="Wire spacer plate bundle configuration.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_spacer_long": dict(
        name_long="Wire Bundles: Wire Spacer Long",
        description="Long wire spacer plate bundle configuration.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wire_spacer_u": dict(
        name_long="Wire Bundles: Wire Spacer U",
        description="U-shaped wire spacer plate bundle configuration.",
        category="Wire Bundles",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    # ── Misc legacy ──────────────────────────────────────────────────────────
    "trt_old": dict(
        name_long="Other: TRT Old (Legacy)",
        description="Legacy TRT component; delegates to oobb_get_items_oobb_old.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "wheel_old_1": dict(
        name_long="Other: Wheel (Legacy Revision 1)",
        description="Legacy wheel component; delegates to oobb_get_items_oobb_old.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
    "ziptie_holder_jack": dict(
        name_long="Other: Ziptie Holder Jack",
        description="Ziptie holder jack component; delegates to oobb_get_items_oobb_old.",
        category="Other",
        shape_aliases=[],
        returns="List of geometry component dicts.",
        variables=[],
    ),
}

# ── writer ────────────────────────────────────────────────────────────────────

def build_define_block(name: str, data: dict) -> str:
    aliases = data.get("shape_aliases", [])
    returns = data.get("returns", "List of geometry component dicts.")
    variables = data.get("variables", [])

    var_lines = ""
    for v in variables:
        var_lines += f'    v.append({{"name": {v["name"]!r}, "description": {v["description"]!r}, "type": {v["type"]!r}, "default": {v["default"]!r}}})\n'

    return (
        f'def describe():\n'
        f'    global d\n'
        f'    d = {{}}\n'
        f'    d["name"] = {name!r}\n'
        f'    d["name_long"] = {data["name_long"]!r}\n'
        f'    d["description"] = {data["description"]!r}\n'
        f'    d["category"] = {data["category"]!r}\n'
        f'    d["shape_aliases"] = {aliases!r}\n'
        f'    d["returns"] = {returns!r}\n'
        f'    v = []\n'
        f'{var_lines}'
        f'    d["variables"] = v\n'
        f'    return d\n'
        f'\n'
        f'\n'
        f'def define():\n'
        f'    global d\n'
        f'    if not isinstance(d, dict) or not d:\n'
        f'        describe()\n'
        f'    defined_variable = {{}}\n'
        f'    defined_variable.update(d)\n'
        f'    return defined_variable'
    )


# Match an optional existing describe() block followed by define() — idempotent re-runs
DEFINE_RE = re.compile(r'(?:def describe\(\):.*?\n\n+)?def define\(\):.*?(?=\ndef |\Z)', re.DOTALL)


def patch_file(path: Path, name: str, data: dict) -> bool:
    content = path.read_text(encoding="utf-8")
    new_block = build_define_block(name, data)
    new_content, count = DEFINE_RE.subn(new_block, content, count=1)
    if count == 0:
        print(f"  WARN: no define() found in {path}")
        return False
    path.write_text(new_content, encoding="utf-8")
    return True


if __name__ == "__main__":
    root = Path(__file__).parent / "components"
    updated = 0
    skipped = 0
    for name, data in DEFINES.items():
        wp = root / name / "working.py"
        if not wp.exists():
            print(f"  SKIP (no file): {name}")
            skipped += 1
            continue
        if patch_file(wp, name, data):
            print(f"  OK: {name}")
            updated += 1
        else:
            skipped += 1

    print(f"\nDone: {updated} updated, {skipped} skipped.")
